version: '3.1'

# with help from https://stackoverflow.com/questions/61800182/how-to-route-angular-app-inside-nginx-container

services:
  frontend:
    container_name: rapidproto-web
#    depends_on:
#      - backend
    image: rapidproto-web
    build:
      context: ./
      dockerfile: frontend.dockerfile
    ports:
      - "80:80"

  backend:
    container_name: rapidproto-api
    image: rapidproto-api
    build:
      context: ./
      dockerfile: backend.dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
