version: '3.1'

# with help from https://stackoverflow.com/questions/61800182/how-to-route-angular-app-inside-nginx-container

services:
  frontend:
    container_name: rapidproto-web
    depends_on:
      - backend
    image: rapidproto-web
    build:
      context: ./
      dockerfile: frontend.dockerfile
    environment:
      - BACKEND_API_HOST=http://localhost
      - BACKEND_API_PORT=3333
      - BACKEND_API_PREFIX=api
      - BACKEND_API_TIMEOUT=3000
    ports:
      - "80:80"

  backend:
    container_name: rapidproto-api
    image: rapidproto-api
    build:
      context: ./
      dockerfile: backend.dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3334
      - GLOBAL_PREFIX=api
    ports:
      - "3333:3334"
